# .github/workflows/main_SAITSnowScore.yml (or similar name)

name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - Azure-Branch  # <-- CHANGED: Triggers on your specific branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      # Add your Clerk Secret Key here if needed for build steps
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }} 

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SAITSnowScore' # <-- CHANGED: Targets your specific App Service
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_YOURSECRETCODE }} # <-- CHECK THIS IN STEP 2
          package: .
